### ISSUE TITLE
Issues with "round duration"

### ISSUE THREAD

**Issue by museack** [simplecrypto/simplecoin_multi#180]
Having weird issues with the Round Duration display...  
It resets every time I refresh the screen.  

On my first test with simplecoin, I had the problem at first with an SHA256 pool that went away...  perhaps after I added in a Scrypt pool?  But at that point the scrypt pool was doing the same thing... resetting to 00:00:00 when I reload the page. 

Setting up a new installation of simplecoin_multi, I currently just have a SHA256 pool, and Round Duration is doing the same thing... resetting to 00:00 every time I refresh the page.  Will add a scrypt pool in the next couple days and will report back.

**Comment by ericecook** [comment]
Yup, this is a known issue (#158) so I'm gonna close this ticket as a duplicate.

For performance reasons the block timer showed on the pool stats page starts from the last solved block, so until you've solved the first block the timer will just always start at 0.
