### ISSUE TITLE
Looking for correct syntax for vardiff enabled stratum in config.toml

### ISSUE THREAD

**Issue by museack** [simplecrypto/simplecoin_multi#181]
# Each of these is a port. Monitor address must match up to a PP stratum
# monitor endpoint
[mining_servers.1]
address = "localhost"
monitor_address = "http://localhost:3855/stratum"
port = 3333
location = "CA"
diff = 1
chain = 1

If powerpool's diff is set to Vardiff, what is the diff setting supposed to be above?  I've tried a number of different number combinations and "vardiff", nothing seems to work.

**Comment by museack** [comment]
got answer from sigwo on irc...
diff = "8 - 1024" 
I didn't try using quotes..

**Comment by ericecook** [comment]
I added some comments to the example 5f98439b24fe79350654cc8a4548cf97fdb5bf44, hopefully that'll make it clearer for future users.

All cleared up now?
