### ISSUE TITLE
Fee not being applied

### ISSUE THREAD

**Issue by crackfoo** [simplecrypto/simplecoin_multi#187]
Hi, 

I've set in my scm config.coml on my profit switching a fee however, when blocks are found, it is now applying the fee.

[chains.1]
title = "Profit Switch Sha256"
algo = "sha256"
type = "pplns"
currencies = ["NEOS", "TIT", "WANK", "FFC"]
last_n = 2
fee_perc = "0.03"

However:

Coinbase Value	120.00 FFC (with 0.000000 in fees)

Any idea's why fee are not applied?

Thanks

**Comment by ericecook** [comment]
That config looks fine. Please double check that your PowerPool config is mining & reporting to chain 1

**Comment by crackfoo** [comment]
redis_sha256:
    type: powerpool.reporters.RedisReporter
    pool_report_configs:
        - worker_format_string: "{chain}"
          user: "pool"
        - worker_format_string: "{currency}"
          user: "pool_currency"
          report_merge: False
    attrs:
        chain: "SWITCH-SHA256"
    redis:
        port: 6379
    chain: 1

**Comment by crackfoo** [comment]
There are 2 "chain" values in the reporter... should they both be 1?

**Comment by ericecook** [comment]
That is your problem - take a look at the example https://github.com/simplecrypto/powerpool/blob/master/config.example.yml#L134
