### ISSUE TITLE
Can't generate valid signature verification

### ISSUE THREAD

**Issue by mkminer** [simplecrypto/simplecoin_multi#190]
I have tried this several times and different ways. I current have a 1 coin site and I cannot generation a valid signature so I can utilize the auto-payout process. Every time I go through the process when I submit the signature and update settings, it comes back with "not a valid signature". Not quite sure how to debug this. If I verify the signature in the wallet, it says it's fine.

Thoughts?

Thanks,
MK Miner

**Comment by ericecook** [comment]
If it is getting rejected you can look at the error in the webserver log. IIRC all attempts are logged atm, whether successful or not.

To nail down the exact problem you can look at the possible outputs at the bottom of utils.py. Some of them are piped straight from the coinserver

**Comment by mkminer** [comment]
Thanks, Eric.

The problem (and it may be a bug) was that the "site_title" was not
matching signature. The site_title was "MK Mining" and the signature
verification was seeing "MK", so it's not handling the "space". I replaced
the title with "MK-Mining" and it seems to make it further.

Thanks again,

MK Miner



Mark Spehalski
markspehalski@gmail.com
503-484-3539

**Comment by ericecook** [comment]
Great, glad you got it figured out. I'll add a note about spaces in the site_title
